name: BuildPaoloEngine

on: 
  push:
    branches:
    - main
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build!!!
        run: msbuild ./fisica2-main/PhysicsGame.sln

      - name: Create artifact directory
        run: |
          mkdir ./artifact
          mkdir ./artifact/PhysicsGame
        
      - name: Copy files
        run: copy ./Build/PhysicsGame/Release/win32/PhysicsGame.exe ./artifact/PhysicsGame/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: Windows-Binary
          path: ./artifact/
